export { default as AppRating } from './specs/AppRating.nitro'
export { default as Clipboard } from './specs/Clipboard.nitro'
export { default as Compressor } from './specs/Compressor.nitro'
export { default as Contacts } from './specs/Contacts.nitro'
export { default as DeviceInfo } from './specs/DeviceInfo.nitro'
export { default as Documents } from './specs/Documents.nitro'
export { default as FileSystem } from './specs/FileSystem.nitro'
export { default as GeoLocation } from './specs/GeoLocation.nitro'
export { default as Localize } from './specs/Localize.nitro'
export { default as Mime } from './specs/Mime.nitro'
export { default as Permissions } from './specs/Permissions.nitro'
export { default as Screenshot } from './specs/Screenshot.nitro'
export { default as SoundPlayer } from './specs/SoundPlayer.nitro'
export { default as SoundRecorder } from './specs/SoundRecorder.nitro'
export { default as Uuid } from './specs/Uuid.nitro'
export { default as Volume } from './specs/Volume.nitro'

